apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: podkrepi.bg
      http:
        paths:
          - backend:
              service:
                name: frontend-headless
                port:
                  number: 3040
            pathType: ImplementationSpecific
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: api-headless
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: api-headless
                port:
                  number: 80
          - path: /swagger-json
            pathType: Prefix
            backend:
              service:
                name: api-headless
                port:
                  number: 80

  tls:
    - hosts:
        - podkrepi.bg
