name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    needs: [check-label]
    uses: ./.github/workflows/tests.yml
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
      MONDOO_SECRET: ${{ secrets.MONDOO_SECRET }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}